### ISSUE TITLE
TypeError AdvancedSearch\Module::createDefaultSearchConfig() 

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/Omeka-S-module-AdvancedSearch#11]
I'm unable to install Advanced Search 3.4.18 on a fresh install of Omeka S version 4.0.4. When attempting to install Advanced Search 3.4.16, 3.4.17 and 3.4.18 I get the error below.

TypeError
AdvancedSearch\Module::createDefaultSearchConfig(): Return value must be of type int, string returned

Details:

TypeError: AdvancedSearch\Module::createDefaultSearchConfig(): Return value must be of type int, string returned in /omekas/modules/AdvancedSearch/Module.php:1314
Stack trace:
#0 /omekas/modules/AdvancedSearch/Module.php(1195): AdvancedSearch\Module->createDefaultSearchConfig()
#1 /omekas/nwdh/modules/AdvancedSearch/Module.php(166): AdvancedSearch\Module->installResources()
#2 /omekas/modules/Common/TraitModule.php(99): AdvancedSearch\Module->postInstall()
#3 /omekas/application/src/Module/Manager.php(226): AdvancedSearch\Module->install(Object(Laminas\ServiceManager\ServiceManager))
#4 /omekas/application/src/Controller/Admin/ModuleController.php(117): Omeka\Module\Manager->install(Object(Omeka\Module\Module))
#5 /omekas/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->installAction()
#6 /omekas/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#7 /omekas/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#8 /omekas/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#9 /omekas/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#10 /omekas/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#11 /omekas/nwdh/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#12 /omekas/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#13 /omekas/index.php(21): Laminas\Mvc\Application->run()
#14 {main}

Installed and active modules are:
Common 3.4.47
Reference 3.4.47

Theme:
Default

**Comment by adehner** [comment]
This has been resolved with 3.4.20
Thank you!
