### ISSUE TITLE
Error when editing configuration - `Unknown named parameter $context_key`

### ISSUE THREAD

**Issue by giocomai** [Daniel-KM/Omeka-S-module-AdvancedSearch#15]
Trying to save changes to configuration in the search manager leads to this error. More specifically, just opening the configuration settings page - `/admin/search-manager/config/1/configure` and trying to save, even if nothing is changed, leads to the error below. 

```
 Error
Unknown named parameter $context_key

Dettagli:

Error: Unknown named parameter $context_key in /var/www/html/vendor/laminas/laminas-validator/src/Callback.php:139
Stack trace:
#0 /var/www/html/vendor/laminas/laminas-validator/src/ValidatorChain.php(242): Laminas\Validator\Callback->isValid(Array, Array)
#1 /var/www/html/vendor/laminas/laminas-inputfilter/src/Input.php(410): Laminas\Validator\ValidatorChain->isValid(Array, Array)
#2 /var/www/html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(273): Laminas\InputFilter\Input->isValid(Array)
#3 /var/www/html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(226): Laminas\InputFilter\BaseInputFilter->validateInputs(Array, Array, NULL)
#4 /var/www/html/vendor/laminas/laminas-inputfilter/src/CollectionInputFilter.php(225): Laminas\InputFilter\BaseInputFilter->isValid(NULL)
#5 /var/www/html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(250): Laminas\InputFilter\CollectionInputFilter->isValid(NULL)
#6 /var/www/html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(226): Laminas\InputFilter\BaseInputFilter->validateInputs(Array, Array, NULL)
#7 /var/www/html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(250): Laminas\InputFilter\BaseInputFilter->isValid(NULL)
#8 /var/www/html/vendor/laminas/laminas-inputfilter/src/BaseInputFilter.php(226): Laminas\InputFilter\BaseInputFilter->validateInputs(Array, Array, NULL)
#9 /var/www/html/vendor/laminas/laminas-form/src/Form.php(481): Laminas\InputFilter\BaseInputFilter->isValid()
#10 /var/www/html/volume/modules/AdvancedSearch/src/Controller/Admin/SearchConfigController.php(209): Laminas\Form\Form->isValid()
#11 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): AdvancedSearch\Controller\Admin\SearchConfigController->configureAction()
#12 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#14 /var/www/html/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#15 /var/www/html/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#16 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#17 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#18 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#19 /var/www/html/index.php(21): Laminas\Mvc\Application->run()
#20 {main}
```

On the top of the page I also see a separate message, which may be unrelated:

```
 Deprecated: Creation of dynamic property AdvancedSearch\Controller\Admin\SearchConfigController::$formElementManager is deprecated in /var/www/html/volume/modules/AdvancedSearch/src/Controller/Admin/SearchConfigController.php on line 70
```

**Comment by Daniel-KM** [comment]
This is probably the same issue than #14. The module works fine with php 7.4 but not php 8. Which is your version?

I fixed it in a case modifying the php version of the server and revert it and now saving works fine, but it's only a workaround.

**Comment by Daniel-KM** [comment]
Is it fixed with last version?

**Comment by Daniel-KM** [comment]
The issue was here : https://www.php.net/manual/fr/function.call-user-func-array.php#125953
