### ISSUE TITLE
Issue installing AdvancedSearch-3.4.36

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-AdvancedSearch#21]
When I try to upgrade to AdvancedSearch-3.4.36 I first get an error which says that I need to upgrade the Common module to 3.4.64 (isn't there a better way of providing feedback on required modules prior to upgrading??). After installing Common-3.4.64 I get the following error on the AdvancedSearch-3.4.36 install:
```
TypeError: AdvancedSearch\Module::AdvancedSearch\{closure}(): Argument #1 ($linksIn) must be of type array, null given, called in /home/http/goudatijdmachine.nl/omeka-s-modules/AdvancedSearch/data/scripts/upgrade.php on line 1787 and defined in /home/http/goudatijdmachine.nl/omeka-s-modules/AdvancedSearch/data/scripts/upgrade.php:1772
Stack trace:
#0 /home/http/goudatijdmachine.nl/omeka-s-modules/AdvancedSearch/data/scripts/upgrade.php(1787): AdvancedSearch\Module->AdvancedSearch\{closure}()
#1 /home/http/goudatijdmachine.nl/omeka-s-modules/Common/TraitModule.php(366): require_once('...')
#2 /home/http/goudatijdmachine.nl/omeka-s-modules/Common/TraitModule.php(354): AdvancedSearch\Module->postUpgradeAuto()
#3 /home/http/goudatijdmachine.nl/omeka-s-modules/Common/TraitModule.php(161): AdvancedSearch\Module->postUpgrade()
#4 /home/http/goudatijdmachine.nl/omeka-s-4.1.1/application/src/Module/Manager.php(304): AdvancedSearch\Module->upgrade()
#5 /home/http/goudatijdmachine.nl/omeka-s-4.1.1/application/src/Controller/Admin/ModuleController.php(250): Omeka\Module\Manager->upgrade()
#6 /home/http/goudatijdmachine.nl/omeka-s-4.1.1/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\Admin\ModuleController->upgradeAction()
#7 /home/http/goudatijdmachine.nl/omeka-s-4.1.1/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
```

**Comment by Daniel-KM** [comment]
I repushed the module, can you retry?

**Comment by coret** [comment]
I retried with the zip from https://github.com/Daniel-KM/Omeka-S-module-AdvancedSearch/releases/tag/3.4.36 but get the same error: `TypeError: AdvancedSearch\Module::AdvancedSearch\{closure}(): Argument #1 ($linksIn) must be of type array, null given, called in /home/http/goudatijdmachine.nl/omeka-s-modules/AdvancedSearch/data/scripts/upgrade.php on line 1787 and defined in /home/http/goudatijdmachine.nl/omeka-s-modules/AdvancedSearch/data/scripts/upgrade.php:1772`

**Comment by Daniel-KM** [comment]
Can you try here again?

**Comment by coret** [comment]
Installed OK!
