### ISSUE TITLE
Navigation Link Route Error

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/Omeka-S-module-AdvancedSearch#7]
When adding an Advanced Search page to my site’s navigation menu, I get the error below. I would just remove the page from my nav menu, but the error locks me out of navigation menu editing.

Omeka v.3.2.3
Advanced Search v.3.4.6.20

`Laminas\Router\Exception\RuntimeException
Route with name "search-page-4" not found

Details:

Laminas\Router\Exception\RuntimeException: Route with name "search-page-4" not found in /vendor/laminas/laminas-router/src/Http/TreeRouteStack.php:355
Stack trace:
#0 /vendor/laminas/laminas-view/src/Helper/Url.php(105): Laminas\Router\Http\TreeRouteStack->assemble(Array, Array)
#1 /application/src/View/Helper/Url.php(34): Laminas\View\Helper\Url->__invoke('search-page-4', Array, Array, false)
#2 /application/src/Site/Navigation/Translator.php(168): Omeka\View\Helper\Url->__invoke('search-page-4', Array, Array)
#3 /application/src/Site/Navigation/Translator.php(89): Omeka\Site\Navigation\Translator->getLinkUrl(Object(AdvancedSearch\Site\Navigation\Link\SearchPage), Array, Object(Omeka\Api\Representation\SiteRepresentation))
#4 /application/src/Site/Navigation/Translator.php(96): Omeka\Site\Navigation\Translator->Omeka\Site\Navigation\{closure}(Array)
#5 /application/src/Controller/SiteAdmin/IndexController.php(229): Omeka\Site\Navigation\Translator->toJstree(Object(Omeka\Api\Representation\SiteRepresentation))
#6 /vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\SiteAdmin\IndexController->navigationAction()
#7 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#11 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#12 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#13 /vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#14 /index.php(21): Laminas\Mvc\Application->run()
#15 {main}
`

**Comment by adehner** [comment]
This wasn't a theme compatibility issue. It's an Advanced Search issue. Either it's a glitch or it's a problem with my configuration.

I have 2 sites and 2 search configs. I want to use the 2 search configs on both sites. Both search configs are active for both sites. 

I can add 1 search config to the navigation menu of both sites. If I try to add the 2nd config, I get this error: 

 Laminas\Router\Exception\RuntimeException
Route with name "search-page-2" not found

Details:

Laminas\Router\Exception\RuntimeException: Route with name "search-page-2" not found in /home/annelies/public_html/plpr4/vendor/laminas/laminas-router/src/Http/TreeRouteStack.php:364
Stack trace:
#0 /home/annelies/public_html/plpr4/vendor/laminas/laminas-view/src/Helper/Url.php(107): Laminas\Router\Http\TreeRouteStack->assemble(Array, Array)
#1 /home/annelies/public_html/plpr4/application/src/View/Helper/Url.php(34): Laminas\View\Helper\Url->__invoke('search-page-2', Array, Array, false)
#2 /home/annelies/public_html/plpr4/application/src/Site/Navigation/Translator.php(168): Omeka\View\Helper\Url->__invoke('search-page-2', Array, Array)
#3 /home/annelies/public_html/plpr4/application/src/Site/Navigation/Translator.php(89): Omeka\Site\Navigation\Translator->getLinkUrl(Object(AdvancedSearch\Site\Navigation\Link\SearchPage), Array, Object(Omeka\Api\Representation\SiteRepresentation))
#4 /home/annelies/public_html/plpr4/application/src/Site/Navigation/Translator.php(96): Omeka\Site\Navigation\Translator->Omeka\Site\Navigation\{closure}(Array)
#5 /home/annelies/public_html/plpr4/application/src/Controller/SiteAdmin/IndexController.php(228): Omeka\Site\Navigation\Translator->toJstree(Object(Omeka\Api\Representation\SiteRepresentation))
#6 /home/annelies/public_html/plpr4/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\SiteAdmin\IndexController->navigationAction()
#7 /home/annelies/public_html/plpr4/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /home/annelies/public_html/plpr4/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /home/annelies/public_html/plpr4/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /home/annelies/public_html/plpr4/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#11 /home/annelies/public_html/plpr4/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#12 /home/annelies/public_html/plpr4/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#13 /home/annelies/public_html/plpr4/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#14 /home/annelies/public_html/plpr4/index.php(21): Laminas\Mvc\Application->run()
#15 {main}

I've deactivated all plugins, and there is no incompatibility there. I have tried attaching the configs to the sites in each site's siteadmin settings and also within the search config. Neither method makes a difference.

Omeka 4.0.4
Advanced Search (3.4.20), Block Plus (3.4.20), CSV Import (2.5.1), Common (3.4.49), Custom Ontology (3.4.5.1), Data Type RDF (3.4.8), File Sideload (1.7.1), Internationalisation (3.4.13), Mapping (1.10.0), Menu (3.4.8), Numeric Data Types (1.11.3), Random Items Block (0.3.0), Reference (3.4.47)

**Comment by adehner** [comment]
@Daniel-KM I'm able to add the second search config using the Menu module, but I cannot add it to the core Navigation

**Comment by Daniel-KM** [comment]
Can you retry with last version of the module?

**Comment by Daniel-KM** [comment]
Fixed in last versions.
